name = "polyglottos-api"
main = "./src/index.ts"
workers_dev = true
compatibility_date = "2023-10-01"

[env.production]
name = "api-production"

define = { "process.env.PRISMA_CLIENT_ENGINE_TYPE" = "edge" }

[env.local]
name = "api-local"

define = { "process.env.PRISMA_CLIENT_ENGINE_TYPE" = "library" }