name = "polyglottos-api"
main = "./src/index.ts"
workers_dev = true
compatibility_date = "2023-10-01"

[env.production]
name = "api-production"

[env.local]
name = "api-local"

[[d1_databases]]
binding = "DB"
database_name = "polyglottos_db"
database_id = "${D1_DATABASE_ID}" 

[observability]
enabled = true