name = "api"
main = "./src/index.ts"
account_id = "${CF_ACCOUNT_ID}"
workers_dev = true
compatibility_date = "2023-10-01"

upload = { format = "service-worker" }

[env.production]
name = "api-production"
