name = "polyglottos-api"
main = "./src/index.ts"
workers_dev = true
compatibility_date = "2023-10-01"

[env.production]
name = "api-production"

[env.local]
name = "api-local"

[[d1_databases]]
binding = "DB"
database_name = "polyglottos_db"
database_id = "1492d3bf-a471-4c29-b337-08f8a90dd6eb"

[observability]
enabled = true