name: Deploy API

on:
  push:
    paths:
      - 'apps/api/**'
      - '.github/workflows/deploy-api.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npx prisma generate --no-engine
        working-directory: ./apps/api

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./apps/api
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
