name: Migrate Database

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/src/db/**'
      - 'apps/api/drizzle/**'
      - 'apps/api/drizzle.config.ts'
      - 'apps/api/src/db_migrate.sh'
      - '.github/workflows/migrate-database.yml'

jobs:
  migrate:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'

      - name: Install dependencies
        run: npm install
        working-directory: ./apps/api

      - name: Generate Drizzle client and Apply Migrations
        run: npm run db:migrate
        working-directory: ./apps/api
        env:
          D1_DATABASE_ID: ${{ secrets.D1_DATABASE_ID }}
