name = "polyglottos-landing-page"

[build]
command = "rm package-lock.json && npm install --verbose && npm run build --verbose"
compatibility_date = "2024-12-08"
pages_build_output_dir = "build/client"

[env]
NODE_VERSION = "22.12.0"